version: "3"
services:
  generate-reports:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      TZ: "IST"
      NODE_ENV: "dev"
      APP_IP: "0.0.0.0"
      NODE_OPTIONS: "--max-old-space-size=4096"
      MONGO_URL: "mongodb://ashieldUser:ASh1e19U_21@172.31.0.1:27017/"
      BLOB_ACCOUNT_NAME: ""
      BLOB_ACCOUNT_KEY: ""
      BLOB_CONTAINER_NAME: ""
      BLOB_NAME: ""
    volumes:
      - ./out:/app/out
    command: [ "npm", "start" ]
